name: vvims
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_staggered_animations: ^1.0.0
  flutter_animate: ^4.5.0
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.2.0
  rive: ^0.13.13
  provider: ^6.1.2
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    
  - lib/assets/images/
  - lib/assets/images/Rive/
    
